"""Initial migration

Revision ID: 53593ff7dde0
Revises: 
Create Date: 2025-02-16 02:05:37.940999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53593ff7dde0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('view_order',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['view_order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('view_order',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
