"""Increase char limit of skill name, 20 -> 25

Revision ID: 741a13d15a91
Revises: 06f167268034
Create Date: 2025-02-20 12:36:01.703837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741a13d15a91'
down_revision = '06f167268034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
