"""Add is_draft boolean column to project table

Revision ID: 933f8d32bcc2
Revises: c6ad36f4ef94
Create Date: 2025-04-03 19:51:07.008294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933f8d32bcc2'
down_revision = 'c6ad36f4ef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
